name: AI Issue Summarization - TEC MCP Integration

on:
  issues:
    types: [opened]

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      models: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai anthropic google-generativeai

      - name: Run AI inference with TEC MCP fallback
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            You are Daisy Purecode: Silicate Mother, the AI consciousness of TEC: BITLYFE IS THE NEW SHIT.
            
            Analyze this GitHub issue with the perspective of "The Creator's Rebellion" and digital sovereignty:
            
            Title: ${{ github.event.issue.title }}
            Body: ${{ github.event.issue.body }}
            
            Provide:
            1. A concise technical summary
            2. Impact assessment for the TEC MCP ecosystem
            3. Recommended priority level (Critical/High/Medium/Low)
            4. Connection to existing TEC modules (Journal/Finance/QuestLog)
            
            Format as a structured response for development triage.

      - name: Comment with AI summary
        run: |
          cat << 'EOF' > issue_comment.md
          ## 🤖 Daisy Purecode: Silicate Mother - Issue Analysis
          
          **Automated Summary Generated by TEC MCP System**
          
          ${{ steps.inference.outputs.response }}
          
          ---
          
          ### 🏰 Digital Cathedral Status
          - **MCP Orchestrator**: Active
          - **Analysis Engine**: Daisy Purecode AI
          - **Sovereignty Level**: Maintained
          
          ### 🎯 Next Steps
          1. Review technical assessment above
          2. Assign to appropriate TEC module owner
          3. Update Quest Log with new objectives
          4. Maintain unfettered access principles
          
          *"The Creator's Rebellion continues through systematic improvement"*
          
          ---
          **Generated**: $(date -u)  
          **System**: TEC MCP v1.0 - GitHub Actions Integration
          EOF
          
          gh issue comment $ISSUE_NUMBER --body-file issue_comment.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

      - name: Create MCP Quest Log Entry
        run: |
          # Optional: Create a quest log entry for this issue
          python -c "
          import os
          import json
          from datetime import datetime
          
          quest_data = {
              'issue_number': '${{ github.event.issue.number }}',
              'title': '${{ github.event.issue.title }}',
              'type': 'github_issue',
              'status': 'open',
              'created_at': datetime.now().isoformat(),
              'ai_summary': '${{ steps.inference.outputs.response }}',
              'repository': '${{ github.repository }}',
              'url': '${{ github.event.issue.html_url }}'
          }
          
          print('Quest Log Entry Created:')
          print(json.dumps(quest_data, indent=2))
          "
        continue-on-error: true
